# Generated by Django 3.0.6 on 2020-06-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200601_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='password',
            field=models.CharField(default='compass12!askdnakwnnd', max_length=20),
            preserve_default=False,
        ),
    ]
